### ISSUE TITLE
SEALS: Similarity Search for Efficient Active Learning and Search of Rare Concepts

### ISSUE THREAD

**Issue by kayuksel** [webis-de/small-text#12]
Hello, thank you for open-sourcing this project. I would like to suggest adding the following method to the library:
"Similarity Search for Efficient Active Learning and Search of Rare Concepts" Link: https://arxiv.org/abs/2007.00077
It seems that it can it well in this library, it is also possible to combine that with other methods. Sincerely, Kamer

**Comment by chschroeder** [comment]
Hi, this looks really interesting, thank you! I will look into it.

**Comment by chschroeder** [comment]
Update: I have a working implementation by now. Unfortunately, this showed me that the strategies which I wanted to combine with SEALS, mainly the ones inheriting from `EmbeddingBasedQueryStrategy`, are currently suboptimal and the performance gain does not carry over to them.

Next, I need first improve the `EmbeddingBasedQueryStrategy` class but I really like this approach, and I will likely add it to small-text soon.

**Comment by kayuksel** [comment]
Amazing, thanks a lot! Looking forward.
