### ISSUE TITLE
Pass local_files_only kwarg in TransformerBasedClassification

### ISSUE THREAD

**Issue by chschroeder** [webis-de/small-text#17]
## Feature description

Provide a way to set `local_files_only` in TransformerBasedClassification. 
https://github.com/huggingface/transformers/issues/2867

## Motivation

The integration tests are too slow and a majority of the time can be avoided with this setting. Moreover, in environments without an internet connection the current state will fail.

## Addition comments

-

**Comment by James4Ever0** [comment]
search for "[from_pretrained](https://github.com/webis-de/small-text/search?q=from_pretrained)" then add parameters like "[local_files_only](https://github.com/huggingface/transformers/issues/2867)" or "[local_files_first](https://github.com/huggingface/transformers/issues/20875)"

**Comment by chschroeder** [comment]
Thanks for your input! This has also been on my todo list for a while. I have started to work on this and it will be part of the next release.
