### ISSUE TITLE
small-text for named entity recognition model

### ISSUE THREAD

**Issue by glahoti6** [webis-de/small-text#22]
Can small-text be used with BERT-based NER / token classification model?

**Comment by chschroeder** [comment]
Unfortunately, it does not support token classification yet.

However, for Transformer Models a rough solution should be achievable with just a few changes to the classifier and query strategies. And the dataset abstraction probably will need to be adapted here and there.

Nevertheless, it's not on my roadmap for the near future but if you anyone wants to try a prototype I would be willing to help.
